### ISSUE TITLE
header.html - зайві пробіли

### ISSUE THREAD

**Issue by Vitavanika** [Vitavanika/project-group-14#10]
![image](https://github.com/user-attachments/assets/c15888af-b2c4-4f7d-8090-2d772baf8209)

**Comment by LiudmylaTar** [comment]
Привіт,
я поправлю, але на скільки я розумію то саме для цього тегу вони не критичні
1. Як браузери обробляють пробіли
Браузери автоматично ігнорують зайві пробіли (включаючи переведення рядків, табуляції) між текстом у HTML-коді.
Якщо у тексті всередині тегу є кілька пробілів підряд, вони згортаються в один пробіл.
Наприклад, цей код:
html
<li>  <a href="#hero">  How It Works  </a>  </li>
буде відображений так само, як:
html
Copy code
<li><a href="#hero">How It Works</a></li>

Але також треба відмітити
"Зайві пробіли у тексті HTML не критичні, якщо ви не використовуєте специфічні стилі для збереження пробілів. Але краще слідкувати за чистотою коду для кращої читабельності й підтримки."

**_**Я преберу, всеодно якірь буду оновляти!**_**

То як я памятаю критично для  textarea
Пробіли всередині тегу <textarea>

Усе, що знаходиться між відкриваючим і закриваючим тегами <textarea>, включно з пробілами, переведеннями рядків або текстом, буде вважатися значенням за замовчуванням, яке відобразиться у текстовій області.
Наприклад:
html
<textarea>   Введіть текст...    </textarea>
Цей код відобразить у текстовій області текст із пробілами на початку і в кінці:

"   Введіть текст...    "
Пробіли та переведення рядків у HTML-коді

Якщо ви додаєте переведення рядків або пробіли в коді між тегами <textarea>, вони також потрапляють до вмісту.

Порожнє поле <textarea>
Якщо ви хочете, щоб поле <textarea> було порожнім без зайвих пробілів чи тексту, просто залиште його порожнім:

html
<textarea></textarea>
